import { useId, useState } from 'react';
import { MONTHS, MEASUREMENT_TYPES, kraGroups, weightIssues, resolveKpi, dueMonths, monthlyTarget, achievement, employeeScore, measurement, plannedTarget, allocationSummary, goalPath, percent } from './model';

function F({ label, children }) { const id = useId(); return <div className="pms-field"><label id={id}>{label}</label>{typeof children === 'function' ? children(id) : children}</div>; }
const num = value => value === null || value === undefined ? '—' : Number(value).toLocaleString('en-IN', { maximumFractionDigits: 2 });
export function GoalFields({ goals, people, isAdmin, goal }) {
  if (goal) return <EditGoalFields goal={goal} goals={goals} people={people} />;
  return <NewGoalFields goals={goals} people={people} isAdmin={isAdmin} />;
}

// Scope, parent, department, team and allocation mode are fixed after
// creation (pms_update_goal); an allocated share keeps its parent's unit.
function EditGoalFields({ goal, goals, people }) {
  const allocatedChildren = goals.some(g => g.parentId === goal.id && g.allocation === 'Allocated');
  const unitFixed = goal.allocation === 'Allocated' || allocatedChildren;
  const owners = people.some(p => p.id === goal.ownerId) ? people : [...people, { id: goal.ownerId, name: 'Current owner' }];
  return <>
    <F label="Goal title">{id => <input aria-labelledby={id} name="title" required maxLength="160" defaultValue={goal.title} autoFocus />}</F>
    <F label="Objective">{id => <textarea aria-labelledby={id} name="description" rows="3" maxLength="2000" defaultValue={goal.description} />}</F>
    <p>{goal.scope}{goal.department ? ` · ${goal.department}` : ''}{goal.team ? ` · ${goal.team}` : ''}{goal.parentId ? ` · Parent: ${goalPath(goal.parentId, goals)}` : ''}{goal.parentId ? ` · ${goal.allocation === 'Allocated' ? 'Allocated share' : 'Alignment only'}` : ''}. These can't be changed; delete and recreate the goal to move it.</p>
    <F label="Accountable owner">{id => <select aria-labelledby={id} name="ownerId" required defaultValue={goal.ownerId || ''}><option value="">Select owner</option>{owners.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select>}</F>
    <div className="pms-form-grid"><F label={unitFixed ? 'Annual goal target' : 'Annual goal target (optional for alignment)'}>{id => <input aria-labelledby={id} name="annualTarget" type="number" step="any" min="0.0001" required={unitFixed} defaultValue={goal.annualTarget ?? ''} />}</F><F label="Goal target unit">{id => <input aria-labelledby={id} name="unit" readOnly={unitFixed} defaultValue={goal.unit || ''} placeholder="e.g. INR lakh" />}</F></div>
    {unitFixed && <p>{goal.allocation === 'Allocated' ? 'The unit comes from the parent goal.' : 'Child goals are allocated from this target, so its unit is fixed.'} Check Target planning for allocation balances after saving.</p>}
  </>;
}

function NewGoalFields({ goals, people, isAdmin }) {
  const [scope, setScope] = useState(isAdmin ? 'Company' : 'Department');
  const [parentId, setParentId] = useState('');
  const [allocation, setAllocation] = useState('Aligned');
  const parent = goals.find(g => g.id === parentId);
  const levels = { Company: 0, Department: 1, Team: 2, Individual: 3 };
  const parents = goals.filter(g => levels[g.scope] < levels[scope]);
  return <>
    <F label="Goal title">{id => <input aria-labelledby={id} name="title" required maxLength="160" autoFocus />}</F>
    <F label="Objective">{id => <textarea aria-labelledby={id} name="description" required rows="3" maxLength="2000" />}</F>
    <div className="pms-form-grid">
      <F label="Scope">{id => <select aria-labelledby={id} name="scope" value={scope} onChange={e => { setScope(e.target.value); setParentId(''); setAllocation('Aligned'); }}>{Object.keys(levels).filter(s => isAdmin || s !== 'Company').map(s => <option key={s}>{s}</option>)}</select>}</F>
      {scope !== 'Company' && <F label="Parent objective">{id => <select aria-labelledby={id} name="parentId" required value={parentId} onChange={e => { setParentId(e.target.value); setAllocation('Aligned'); }}><option value="">Select parent objective</option>{parents.map(g => <option value={g.id} key={g.id}>{g.scope}: {g.title}</option>)}</select>}</F>}
      {scope !== 'Company' && <F label="Department">{id => <select aria-labelledby={id} name="department" required>{[...new Set([...people.map(e => e.department), ...goals.map(g => g.department).filter(Boolean)])].map(d => <option key={d}>{d}</option>)}</select>}</F>}
      {scope === 'Team' && <F label="Team name">{id => <input aria-labelledby={id} name="team" required />}</F>}
    </div>
    <F label="Accountable owner">{id => <select aria-labelledby={id} name="ownerId" required><option value="">Select owner</option>{people.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select>}</F>
    {parent && <F label="Contribution to parent">{id => <select aria-labelledby={id} name="allocation" value={allocation} onChange={e => setAllocation(e.target.value)}><option value="Aligned">Alignment only — no numerical roll-up</option>{parent.annualTarget > 0 && <option value="Allocated">Allocated share of parent target</option>}</select>}</F>}
    <div className="pms-form-grid"><F label="Annual goal target (optional for alignment)">{id => <input aria-labelledby={id} name="annualTarget" type="number" step="any" min="0.0001" required={allocation === 'Allocated'} />}</F><F label="Goal target unit">{id => <input key={`${allocation}-${parentId}`} aria-labelledby={id} name="unit" required={allocation === 'Allocated'} readOnly={allocation === 'Allocated'} defaultValue={allocation === 'Allocated' ? parent?.unit : ''} placeholder="e.g. INR lakh" />}</F></div>
    <p>{parent ? `Parent: ${goalPath(parent.id, goals)}` : 'Company objectives are the roots of the alignment tree.'}</p>
    <p>Allocated shares use the same unit and financial year. Alignment alone never adds a child’s result to its parent.</p>
  </>;
}

export function AlignmentView({ goals, kpis, name, onCreate, onEdit, onDelete, goalEditable, canManage, busy }) {
  function node(goal, depth = 0, seen = []) {
    if (seen.includes(goal.id)) return null;
    const children = goals.filter(g => g.parentId === goal.id);
    const allocation = allocationSummary(goal, goals);
    const linked = kpis.filter(k => k.goalId === goal.id);
    return <div className="pms-alignment-node" key={goal.id}>
      <div className="pms-alignment-card"><div><span className="pms-badge">{goal.scope}{goal.team ? ` · ${goal.team}` : ''}</span><h3>{goal.title}</h3><p>{goal.description}</p><small>{goal.department || 'Company-wide'} · {name(goal.ownerId)}</small>{canManage && onEdit && <button className="pms-text-button" disabled={busy || !goalEditable(goal.id)} title={goalEditable(goal.id) ? undefined : 'A submitted or locked scorecard uses this goal. Request a revision first.'} onClick={() => onEdit(goal)}>Edit goal</button>}{canManage && onDelete && (children.length || linked.length
        ? <small className="pms-muted">To delete this goal, first delete its {children.length ? `${children.length} child goal${children.length === 1 ? '' : 's'}` : ''}{children.length && linked.length ? ' and remove its ' : ''}{linked.length ? `${linked.length} linked KPI${linked.length === 1 ? '' : 's'} from ${linked.length === 1 ? 'its scorecard' : 'their scorecards'}` : ''}.</small>
        : <button className="pms-text-button" disabled={busy} onClick={() => onDelete(goal)}>Delete goal</button>)}</div><div className="pms-alignment-numbers"><strong>{goal.annualTarget ? `${num(goal.annualTarget)} ${goal.unit}` : 'Qualitative objective'}</strong><small>{goal.parentId ? goal.allocation === 'Allocated' ? 'Allocated contribution' : 'Alignment only' : 'FY strategic priority'}</small>{goal.annualTarget > 0 && <span className={allocation.remaining < -.001 ? 'pms-validation-error' : ''}>{allocation.status}: {num(Math.abs(allocation.remaining))} {goal.unit}</span>}</div></div>
      {linked.length > 0 && <div className="pms-linked-kpis">{linked.map(k => <span key={k.id}>{k.ownerType === 'Employee' ? name(k.employeeId) : k.ownerId} / {k.kra} / {k.title}{k.sharedSourceId ? ' · shared reference' : ''}</span>)}</div>}
      {children.length > 0 && <div className="pms-alignment-children">{children.map(child => node(child, depth + 1, [...seen, goal.id]))}</div>}
    </div>;
  }
  return <><div className="pms-section-intro"><p>Company → department → team → individual. Alignment and numeric allocation are separate.</p>{canManage && <button className="btn btn-primary" onClick={onCreate}>+ Create goal</button>}</div><div className="pms-notice">Business targets are not employee ratings. Shared KPI references do not multiply the underlying result.</div>{goals.filter(g => !g.parentId || !goals.some(p => p.id === g.parentId)).map(g => node(g))}{!goals.length && <div className="pms-empty"><h3>No goals yet</h3><p>Create a company objective to start the hierarchy.</p></div>}</>;
}

// Mirrors pms_is_hr/pms_is_mgr: only these roles may confirm results or approve scorecards.
const canApprove = p => ['admin', 'superadmin', 'manager', 'hod', 'management'].includes(p.role);

// With `kpi`, edits that KPI (pms_update_kpi): the owner and measurement
// ownership are fixed, and type/frequency freeze once results exist.
export function KpiFields({ people, directory = people, employee, goals, allKpis, ownerType = 'Employee', ownerId, policy, kpi }) {
  const [assigned, setAssigned] = useState(kpi ? (kpi.ownerId || kpi.employeeId) : ownerId || employee?.id || '');
  const [kind, setKind] = useState(kpi?.kind || 'Volume');
  const [sourceId, setSourceId] = useState(kpi?.sharedSourceId || '');
  const [mode, setMode] = useState(kpi?.sharedSourceId ? 'Shared result' : 'Independent');
  const [kra, setKra] = useState(kpi?.kra || '');
  const [kraWeight, setKraWeight] = useState(kpi?.kraWeight ?? 100);
  const [weight, setWeight] = useState(kpi?.weight ?? 100);
  const [frequency, setFrequency] = useState(kpi?.frequency || 'Monthly');
  const [milestones, setMilestones] = useState(kpi?.milestones?.length ? kpi.milestones : [{ id: 'm1', title: '', weight: 50 }, { id: 'm2', title: '', weight: 50 }]);
  const hasResults = !!kpi && Object.keys(kpi.updates || {}).length > 0;
  const ownKpis = allKpis.filter(k => (k.ownerType || 'Employee') === ownerType && (k.ownerId || k.employeeId) === assigned);
  const existingKra = ownKpis.find(k => k.kra === kra && k.id !== kpi?.id);
  const source = allKpis.find(k => k.id === sourceId);
  const sharedSources = allKpis.filter(k => k.ownerType !== 'Employee' && !k.sharedSourceId);
  return <>
    <input name="ownerType" type="hidden" value={ownerType} />
    {kpi ? <>{ownerType === 'Employee' ? <input type="hidden" name="employeeId" value={assigned} /> : <input type="hidden" name="ownerId" value={assigned} />}<p><strong>{ownerType === 'Employee' ? `Employee scorecard: ${directory.find(p => p.id === assigned)?.name || 'Unknown'}` : `${ownerType} scorecard: ${assigned}`}</strong></p></> : ownerType === 'Employee' ? <F label="Assign to employee">{id => <select aria-labelledby={id} name="employeeId" required value={assigned} onChange={e => { setAssigned(e.target.value); setKra(''); }}><option value="" disabled>Select employee</option>{people.map(p => <option key={p.id} value={p.id}>{p.name} · {p.code}</option>)}</select>}</F> : <><input type="hidden" name="ownerId" value={assigned} /><p><strong>{ownerType} scorecard: {assigned}</strong></p></>}
    <F label="KRA / responsibility area">{id => <input aria-labelledby={id} name="kra" value={kra} list="pms-kra-list" onChange={e => setKra(e.target.value)} required autoFocus />}</F><datalist id="pms-kra-list">{kraGroups(ownKpis).map(g => <option key={g.title} value={g.title} />)}</datalist>
    <div className="pms-form-grid"><F label="KRA weight in scorecard (%)">{id => <input aria-labelledby={id} name="kraWeight" type="number" min="1" max="100" step="any" required readOnly={!!existingKra} value={existingKra?.kraWeight ?? kraWeight} onChange={e => setKraWeight(Number(e.target.value))} />}</F><F label="KPI weight within KRA (%)">{id => <input aria-labelledby={id} name="weight" type="number" min="1" max="100" step="any" required value={weight} onChange={e => setWeight(Number(e.target.value))} />}</F></div>
    <div className="pms-notice">Effective final-score contribution: {((existingKra?.kraWeight ?? kraWeight) * weight * policy.kpiWeight / 10000).toFixed(2)}% = KRA × KPI × {policy.kpiWeight}% KPI component.</div>
    <F label="KPI title">{id => <input aria-labelledby={id} name="title" required defaultValue={kpi?.title} />}</F>
    <F label="Aligned goal">{id => <select aria-labelledby={id} name="goalId" required defaultValue={kpi?.goalId}>{goals.map(g => <option key={g.id} value={g.id}>{g.scope}: {g.title}</option>)}</select>}</F>
    <F label="Measurement ownership">{id => <select aria-labelledby={id} value={mode} disabled={!!kpi} onChange={e => setMode(e.target.value)}><option>Independent</option>{ownerType === 'Employee' && <option>Shared result</option>}</select>}</F>
    {mode === 'Shared result' ? <><F label="Authoritative shared KPI">{id => <select aria-labelledby={id} name="sharedSourceId" required disabled={!!kpi} value={sourceId} onChange={e => setSourceId(e.target.value)}><option value="">Select company / department / team KPI</option>{sharedSources.map(k => <option key={k.id} value={k.id}>{k.ownerId} · {k.title}</option>)}</select>}</F><p>{source ? `${source.kind} · ${source.frequency} · ${source.unit}. Targets, actuals and approval come from this source.` : 'Create an organisational KPI first if no shared sources are available.'} This assignment has its own weight but stores no duplicate actuals.</p></> : <>
      <div className="pms-form-grid"><F label="Measurement type">{id => <select aria-labelledby={id} name={hasResults ? undefined : 'kind'} value={kind} disabled={hasResults} onChange={e => setKind(e.target.value)}>{MEASUREMENT_TYPES.map(t => <option key={t}>{t}</option>)}</select>}</F>{hasResults && <input type="hidden" name="kind" value={kind} />}<F label="Reporting frequency">{id => <select aria-labelledby={id} name={hasResults ? undefined : 'frequency'} value={frequency} disabled={hasResults} onChange={e => setFrequency(e.target.value)}><option>Monthly</option><option>Quarterly</option><option>Annual</option></select>}</F>{hasResults && <input type="hidden" name="frequency" value={frequency} />}
      {!['Milestone', 'Rubric', 'Zero incidents'].includes(kind) && <><F label={frequency === 'Monthly' ? 'Monthly target' : `${frequency} target`}>{id => <input aria-labelledby={id} name="target" type="number" min="0.0001" max={kind === 'Rate' ? 100 : undefined} step="any" required defaultValue={kpi && kind === kpi.kind ? kpi.target : undefined} />}</F><F label="Unit">{id => <input key={kind} aria-labelledby={id} name="unit" required readOnly={kind === 'Rate'} defaultValue={kind === 'Rate' ? '%' : kpi && kind === kpi.kind ? kpi.unit : ''} placeholder="e.g. INR lakh, hours, orders" />}</F><F label="Direction">{id => <select aria-labelledby={id} name="direction" defaultValue={kpi?.direction}><option>Higher</option><option>Lower</option></select>}</F></>}
      <F label="Data source">{id => <select aria-labelledby={id} name="dataSource" defaultValue={kpi?.dataSource}><option>Manual</option><option>Imported report reference</option></select>}</F>
      <F label="Data submitter">{id => <select aria-labelledby={id} key={assigned} name="submitterId" required defaultValue={kpi ? kpi.submitterId || '' : assigned}>{directory.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>}</F><F label="Approver">{id => <select aria-labelledby={id} key={assigned} name="approverId" required defaultValue={kpi ? kpi.approverId || '' : directory.find(p => p.id === assigned)?.managerId || directory.find(p => p.id === assigned)?.hodId || ''}><option value="">Select approver</option>{directory.filter(canApprove).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>}</F></div>
      {kind === 'Milestone' && <div className="pms-milestone-editor"><h4>Milestones · weights must total 100%</h4>{milestones.map((m, i) => <div className="pms-form-grid" key={m.id}><F label={`Milestone ${i + 1} title`}>{id => <input aria-labelledby={id} value={m.title} required onChange={e => setMilestones(ms => ms.map(x => x.id === m.id ? { ...x, title: e.target.value } : x))} />}</F><F label={`Milestone ${i + 1} weight (%)`}>{id => <input aria-labelledby={id} value={m.weight} type="number" min="1" max="100" required onChange={e => setMilestones(ms => ms.map(x => x.id === m.id ? { ...x, weight: Number(e.target.value) } : x))} />}</F></div>)}<input name="milestones" type="hidden" value={JSON.stringify(milestones)} /><button className="btn btn-outline" type="button" onClick={() => setMilestones(ms => [...ms, { id: crypto.randomUUID(), title: '', weight: 10 }])}>Add milestone</button></div>}
      {hasResults && <p>Results were already entered for this KPI, so its measurement type and frequency are fixed.</p>}
      {kpi?.targets && <p>This KPI has phased monthly targets. Changing the target, type or frequency resets them to the new target every month.</p>}
      <p>{({ Volume: 'Sum actuals and phased targets across reporting periods.', Rate: 'Enter numerator and denominator; period result is total numerator ÷ total denominator × 100.', 'Weighted average': 'Enter total measured amount and observation count; aggregate the underlying totals.', Snapshot: 'Use the closing value from the last due period, not a sum of balances.', Milestone: 'Completed milestone weights determine achievement. Updates are cumulative.', Rubric: '1–5 anchored rubric: below expectations, developing, meets, exceeds, exceptional.', 'Zero incidents': 'Fixed sample slabs: 0 → 100%, 1 → 70%, 2 → 40%, 3+ → 0%.' })[kind]}</p>
    </>}
  </>;
}

export function MeasurementFields({ kpi, month }) {
  const previous = kpi.updates[month];
  const [applicability, setApplicability] = useState(previous?.applicability || 'Measured');
  return <><F label="Input status">{id => <select aria-labelledby={id} name="applicability" value={applicability} onChange={e => setApplicability(e.target.value)}><option>Measured</option><option>N/A</option></select>}</F>
    {applicability === 'Measured' && (['Rate', 'Weighted average'].includes(kpi.kind) ? <div className="pms-form-grid"><F label={kpi.kind === 'Rate' ? 'Numerator (successful outcomes)' : 'Total measured amount'}>{id => <input aria-labelledby={id} name="numerator" type="number" min="0" step="any" required defaultValue={previous?.numerator ?? ''} />}</F><F label={kpi.kind === 'Rate' ? 'Denominator (eligible outcomes)' : 'Observation count'}>{id => <input aria-labelledby={id} name="denominator" type="number" min="0.0001" step="any" required defaultValue={previous?.denominator ?? ''} />}</F></div> : kpi.kind === 'Milestone' ? <div>{kpi.milestones.map(m => <label className="pms-checkbox" key={m.id}><input name={`milestone:${m.id}`} type="checkbox" defaultChecked={previous?.completed?.includes(m.id)} />{m.title} · {m.weight}%</label>)}</div> : kpi.kind === 'Rubric' ? <F label="Rubric assessment">{id => <select aria-labelledby={id} name="actual" required defaultValue={previous?.actual ?? ''}><option value="">Choose anchored rating</option>{['Below expectations', 'Developing', 'Meets expectations', 'Exceeds expectations', 'Exceptional'].map((label, i) => <option key={label} value={i + 1}>{i + 1} · {label}</option>)}</select>}</F> : <F label={`Actual (${kpi.unit})`}>{id => <input aria-labelledby={id} name="actual" type="number" min="0" step={kpi.kind === 'Zero incidents' ? '1' : 'any'} required defaultValue={previous?.actual ?? ''} />}</F>)}
    <F label={applicability === 'N/A' ? 'Reason not applicable' : 'Progress note / evidence reference'}>{id => <textarea aria-labelledby={id} name="note" rows="3" required defaultValue={previous?.note || ''} />}</F>
    <p>{applicability === 'N/A' ? 'N/A is not zero. This period stays not rated pending an explicit weight/eligibility decision.' : `Target: ${num(monthlyTarget(kpi, month))} ${kpi.unit}. Only confirmed inputs contribute.`}</p>
  </>;
}

export function ScorecardDetails({ kpis, allKpis, goals, months, month, policy, canManage, mode = 'Scorecards', onUpdate, onWeights, onEdit, onRemove, name, busy }) {
  const groups = kraGroups(kpis); const issues = weightIssues(kpis);
  return <><div className={`pms-notice ${issues.length ? 'pms-validation-error' : ''}`}><span>KRA weights: {groups.reduce((n, g) => n + g.weight, 0)} / 100%. {issues.length ? issues.join(' · ') : 'All weight totals are valid.'}</span>{canManage && kpis.length > 0 && <button className="pms-text-button" onClick={onWeights}>Edit weights</button>}</div>
    {groups.map(group => <section className="pms-kra-group" key={group.title}><div className="pms-kra-heading"><div><span className="pms-eyebrow">RESPONSIBILITY AREA</span><h3>{group.title}</h3></div><div><strong>{group.weight}%</strong><small>of scorecard · KPI weights {group.items.reduce((n, k) => n + k.weight, 0)} / 100%</small></div></div>
      {group.items.map(k => { const source = resolveKpi(k, allKpis); const update = source.updates[month]; const result = measurement(k, months, allKpis); const due = dueMonths(source, [month]).length > 0;
        return <article className="pms-panel pms-kpi" key={k.id}><div className="pms-panel-heading"><div><h3>{k.title}</h3><p className="pms-alignment-path">{goalPath(k.goalId, goals)}</p></div><div className="pms-row-actions"><span className="pms-badge">{k.weight}% within KRA</span>{canManage && onEdit && mode === 'Scorecards' && <button className="pms-text-button" disabled={busy} onClick={() => onEdit(k)}>Edit</button>}{canManage && onRemove && mode === 'Scorecards' && <button className="pms-text-button" disabled={busy} onClick={() => onRemove(k)}>Remove</button>}</div></div>
          <div className="pms-kpi-summary"><span>Measurement<strong>{source.kind || 'Volume'} · {source.frequency || 'Monthly'}</strong></span><span>{k.ownerType === 'Employee' ? 'Effective appraisal weight' : 'Effective business score weight'}<strong>{(group.weight * k.weight * policy.kpiWeight / 10000).toFixed(2)}%</strong></span><span>Result / target<strong>{num(result.actual)} / {num(result.target ?? plannedTarget(k, months, allKpis))} {source.unit}</strong></span><span>Achievement<strong>{percent(achievement(k, months, policy.cap, allKpis))}</strong></span></div>
          {k.sharedSourceId && <div className="pms-notice">Shared result from {allKpis.find(x => x.id === k.sharedSourceId)?.ownerId} · {allKpis.find(x => x.id === k.sharedSourceId)?.title}. Read-only reference; enter and approve the measurement once on the organisational scorecard.</div>}
          {mode === 'Monthly updates' ? <div className="pms-update-row"><div><strong>{update?.applicability === 'N/A' ? 'N/A' : num(update?.actual)} / {num(monthlyTarget(source, month))} {source.unit}</strong><p>{update?.note || 'No input submitted.'}</p>{update?.reason && <p className="pms-return-reason">Manager: {update.reason}</p>}</div><span className="pms-badge">{due ? update?.status || 'Not started' : 'Not due'}</span>{!k.sharedSourceId && <button className="btn btn-outline" disabled={busy || !due || ['Submitted', 'Confirmed'].includes(update?.status)} onClick={() => onUpdate(k, month)}>{update?.status === 'Confirmed' ? 'Confirmed' : update?.status === 'Submitted' ? 'Awaiting review' : 'Submit update'}</button>}</div> : <><small>Submitter: {name(source.submitterId || source.employeeId)} · Approver: {name(source.approverId)} · {source.dataSource || 'Manual'}</small><div className="pms-month-grid">{MONTHS.map((m, i) => <div key={m} className={months.includes(i) ? 'selected' : ''}><small>{m}</small><strong>{source.updates[i]?.applicability === 'N/A' ? 'N/A' : num(source.updates[i]?.actual)}</strong><small>{dueMonths(source, [i]).length ? source.updates[i]?.status || 'No update' : 'Not due'}</small></div>)}</div></>}
        </article>;
      })}
    </section>)}
    {!groups.length && <div className="pms-empty"><h3>No KRAs assigned</h3><p>Assign a KPI under a responsibility area to start this scorecard.</p></div>}
  </>;
}

export function WeightFields({ kpis, policy }) {
  const [groups, setGroups] = useState(kraGroups(kpis));
  const draft = groups.flatMap(g => g.items.map(k => ({ ...k, kraWeight: g.weight })));
  const errors = weightIssues(draft);
  return <><input type="hidden" name="weights" value={JSON.stringify(draft.map(k => ({ id: k.id, weight: k.weight, kraWeight: k.kraWeight })))} /><p>KRA weights total 100%; KPI weights total 100% inside each KRA. Effective weight includes the {policy.kpiWeight}% KPI component.</p>{groups.map(g => <fieldset className="pms-weight-fieldset" key={g.title}><legend>{g.title}</legend><F label={`${g.title} KRA weight (%)`}>{id => <input aria-labelledby={id} type="number" min="1" max="100" step="any" required value={g.weight} onChange={e => setGroups(gs => gs.map(x => x.title === g.title ? { ...x, weight: Number(e.target.value) } : x))} />}</F>{g.items.map(k => <div className="pms-weight-row" key={k.id}><F label={`${k.title} KPI weight (%)`}>{id => <input aria-labelledby={id} type="number" min="1" max="100" step="any" required value={k.weight} onChange={e => setGroups(gs => gs.map(x => x.title === g.title ? { ...x, items: x.items.map(v => v.id === k.id ? { ...v, weight: Number(e.target.value) } : v) } : x))} />}</F><span>{(g.weight * k.weight * policy.kpiWeight / 10000).toFixed(2)}% of final score</span></div>)}</fieldset>)}<div className={errors.length ? 'pms-validation-error' : 'pms-notice'}>{errors.length ? errors.join(' · ') : 'All weights total 100%. Ready to save.'}</div></>;
}

export function OrganisationScorecards({ goals, allKpis, people, months, month, policy, onAssign, onUpdate, onWeights, onEdit, onRemove, name, canManage, actorId, onMonthChange, renderWorkflow, editableKpi, isEditable, busy }) {
  const [type, setType] = useState('Department'); const [chosen, setChosen] = useState('');
  const options = type === 'Company' ? ['Company'] : type === 'Department' ? [...new Set([...goals.map(g => g.department), ...people.map(p => p.department)].filter(Boolean))] : [...new Set(goals.filter(g => g.scope === 'Team').map(g => g.team).filter(Boolean))];
  const owner = options.includes(chosen) ? chosen : options[0];
  const kpis = allKpis.filter(k => k.ownerType === type && k.ownerId === owner);
  return <><div className="pms-person-selector"><F label="Scorecard level">{id => <select aria-labelledby={id} value={type} onChange={e => { setType(e.target.value); setChosen(''); }}><option>Company</option><option>Department</option><option>Team</option></select>}</F><F label="Organisational unit">{id => <select aria-labelledby={id} value={owner || ''} onChange={e => setChosen(e.target.value)}>{options.map(o => <option key={o}>{o}</option>)}</select>}</F>{canManage && <button className="btn btn-primary" disabled={!owner || !goals.length || !isEditable(type, owner)} onClick={() => onAssign(type, owner)}>+ Assign organisational KPI</button>}</div><div className="pms-person-card"><div><h3>{owner || 'No unit defined'} · {type} scorecard</h3><p>Business achievement is calculated from this unit’s KPIs, not the average of employee ratings.</p></div><div className="pms-person-score"><strong>{percent(employeeScore(kpis, months, policy.cap, allKpis))}</strong><span>Confirmed business achievement</span></div></div>{renderWorkflow(type, owner)}<ScorecardDetails kpis={kpis} allKpis={allKpis} goals={goals} months={months} month={month} policy={{ ...policy, kpiWeight: 100 }} canManage={canManage && kpis.every(editableKpi)} onUpdate={onUpdate} onWeights={() => onWeights(kpis)} onEdit={onEdit} onRemove={onRemove} name={name} busy={busy} />{kpis.some(k => canManage || k.submitterId === actorId) && <section className="pms-panel"><h3>Enter organisational results · {MONTHS[month]}</h3><F label="Organisation reporting month">{id => <select aria-labelledby={id} value={month} onChange={e => onMonthChange(Number(e.target.value))}>{MONTHS.map((m, i) => <option key={m} value={i}>{m}</option>)}</select>}</F><p>Shared employee KPIs reference these approved measurements.</p>{kpis.filter(k => canManage || k.submitterId === actorId).map(k => <div key={k.id} className="pms-update-row pms-org-input"><span>{k.title} · {k.updates[month]?.status || 'Not started'}</span><button className="btn btn-outline" disabled={['Submitted', 'Confirmed'].includes(k.updates[month]?.status) || !dueMonths(k, [month]).length} onClick={() => onUpdate(k, month)}>Enter result</button></div>)}</section>}</>;
}

export function TargetPlanning({ goals, allKpis, name, onGoalTarget, onPhase, editableKpi, goalEditable, busy }) {
  const [selected, setSelected] = useState('');
  const editable = allKpis.filter(k => !k.sharedSourceId && k.kind === 'Volume' && k.frequency === 'Monthly');
  const kpi = editable.find(k => k.id === selected) || editable[0];
  return <><section className="pms-panel"><h3>Annual goal allocation</h3><p>Only explicit allocated contributions are counted. Alignment-only goals and linked KPI measurements are excluded.</p>{!goals.some(g => g.annualTarget > 0) && <div className="pms-empty"><h3>No numeric goals yet</h3><p>Give a goal an annual target (for example 120 INR lakh) in Goals, then split it across departments and teams here.</p></div>}{goals.filter(g => g.annualTarget > 0).map(g => { const a = allocationSummary(g, goals); return <form key={`${g.id}-${g.annualTarget}`} className="pms-allocation-row" onSubmit={e => { e.preventDefault(); const target = Number(new FormData(e.currentTarget).get('target')); if (!goalEditable(g.id)) return; onGoalTarget(g, target); }}><div><strong>{g.title}</strong><small>{g.scope}{g.unit ? ` · ${g.unit}` : ''} · {num(a.allocated)} allocated to children</small><span className={a.remaining < -.001 ? 'pms-validation-error' : ''}>{a.status}: {num(Math.abs(a.remaining))} {g.unit}</span></div><F label={`${g.title} annual target`}>{id => <input aria-labelledby={id} name="target" type="number" min="0.0001" step="any" required disabled={!goalEditable(g.id)} defaultValue={g.annualTarget} />}</F><button className="btn btn-outline" disabled={busy || !goalEditable(g.id)}>{goalEditable(g.id) ? 'Update allocation' : 'Locked by scorecard'}</button></form>; })}</section><section className="pms-panel"><h3>Monthly target phasing</h3><p>Phase additive volume targets only. Rate, average, snapshot and rubric targets are not divided by 12. Goal allocations and KPI targets are separate draft inputs; changing one does not automatically change the other.</p>{kpi && <F label="KPI to phase">{id => <select aria-labelledby={id} value={kpi.id} onChange={e => setSelected(e.target.value)}>{editable.map(k => <option key={k.id} value={k.id}>{k.title} · {k.ownerType === 'Employee' ? name(k.employeeId) : k.ownerId}</option>)}</select>}</F>}{kpi ? <PhasingForm key={`${kpi.id}-${JSON.stringify(kpi.targets)}`} kpi={kpi} locked={!editableKpi(kpi)} busy={busy} onSave={targets => { if (editableKpi(kpi)) onPhase(kpi, targets); }} /> : <div className="pms-empty"><h3>No KPI to phase yet</h3><p>Only monthly Volume KPIs can be phased. Assign one in Scorecards (measurement type Volume, frequency Monthly) and it will appear here.</p></div>}</section></>;
}

function PhasingForm({ kpi, onSave, locked, busy }) {
  const [targets, setTargets] = useState(MONTHS.map((_, i) => Number(monthlyTarget(kpi, i))));
  const [annual, setAnnual] = useState(targets.reduce((a, b) => a + b, 0));
  const total = targets.reduce((a, b) => a + Number(b), 0);
  const valid = targets.every(t => Number(t) > 0) && Math.abs(total - annual) < .01;
  return <form onSubmit={e => { e.preventDefault(); if (valid && !locked) onSave(targets.map(Number)); }}><fieldset disabled={locked} className="pms-phasing-fields">{locked && <p className="pms-notice">Targets are protected by a submitted or locked scorecard, including shared references. Request a revision first.</p>}<div className="pms-person-selector"><F label="Annual KPI target">{id => <input aria-labelledby={id} type="number" min="0.0001" step="any" required value={annual} onChange={e => setAnnual(Number(e.target.value))} />}</F><button type="button" className="btn btn-outline" onClick={() => setTargets(Array(12).fill(annual / 12))}>Split equally</button></div><div className="pms-target-grid">{MONTHS.map((m, i) => <F key={m} label={`${m} target`}>{id => <input aria-labelledby={id} type="number" min="0.0001" step="any" required value={targets[i]} onChange={e => setTargets(ts => ts.map((t, j) => j === i ? e.target.value : t))} />}</F>)}</div><div className="pms-quarter-totals">{[0, 1, 2, 3].map(q => <span key={q}>Q{q + 1}: <strong>{num(targets.slice(q * 3, q * 3 + 3).reduce((a, b) => a + Number(b), 0))}</strong></span>)}<span>FY: <strong>{num(total)} / {num(annual)}</strong></span></div>{!valid && <p className="pms-validation-error">Monthly targets must be positive and total the annual target.</p>}<button type="submit" disabled={busy || !valid} className="btn btn-primary">Save phased targets</button></fieldset></form>;
}
