-- =============================================================
-- Raniwala portal roles + explicit HODs from HR's HOD.xlsx (26 Sep 2026).
--
-- Reporting managers (manager_id) were already aligned to the same sheet by
-- 20260926_7_raniwala_org_structure_from_hod_sheet.sql -- this migration
-- does NOT touch manager_id. It adds:
--
--   1. profiles.hod_id -- the sheet's HOD per employee. The HOD is not
--      always the manager's manager (e.g. PRAVEEN reports to DEEPAK DHANKAR,
--      whose manager is ARZOO JAIMINY, but PRAVEEN's HOD is BHANU JAIN), so
--      it's stored explicitly; the manager_id chain is only the fallback.
--   2. resolve_leave_approvers / my_team_ids / is_in_team_of honour hod_id.
--   3. Roles: everyone named in the sheet's HOD column -> 'hod'; everyone in
--      the MANAGER column (and not an HOD) -> 'manager'. HR (admin) and
--      Inactive profiles keep their role (POOJA KHANDELWAL stays HR).
--
-- Name resolution (HR-confirmed 26 Sep): 8 aliases by code (RAMESH YADAV =
-- 707, MANOJ SHARMA = 740, ...); PALASH BARMAN = the active POLASH BARMAN
-- profile (see 20260926_7); "ABHISHEK SIR" / "ABHIYANT SIR" (owners, no
-- profile) and SUNIL SONI resolve to nothing -> hod_id NULL, so the chain /
-- HR fallback applies. Employees are matched by EMP CODE; a code the sheet
-- uses for several people (546, 666) also needs the name to agree.
-- =============================================================


-- ── 1. hod_id ─────────────────────────────────────────────────────────────
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hod_id uuid REFERENCES profiles(id) ON DELETE SET NULL;

CREATE OR REPLACE VIEW profile_directory AS
  SELECT id, tenant_id, first_name, middle_name, last_name, employee_id, role, status,
         department, designation, division, manager_id, outlet_id, outlet_location, hod_id
  FROM profiles p
  WHERE tenant_id = (SELECT my_tenant_id()) OR (SELECT my_role()) = 'superadmin';


-- ── 2. Functions ──────────────────────────────────────────────────────────
-- HOD: explicit hod_id when it points at an active HOD, else the first HOD
-- up the manager_id chain. Manager: first active role='manager' ancestor.
CREATE OR REPLACE FUNCTION resolve_leave_approvers(p_profile_id uuid, OUT o_manager uuid, OUT o_hod uuid)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_cur  uuid;
  v_next uuid;
  v_role text;
  v_status text;
  v_chain_hod uuid;
  i int := 0;
BEGIN
  SELECT manager_id INTO v_cur FROM profiles WHERE id = p_profile_id;
  WHILE v_cur IS NOT NULL AND v_cur <> p_profile_id AND i < 8 LOOP
    SELECT role, status, manager_id INTO v_role, v_status, v_next FROM profiles WHERE id = v_cur;
    IF COALESCE(v_status, 'Active') = 'Active' THEN
      IF v_role = 'manager' AND o_manager IS NULL THEN
        o_manager := v_cur;
      ELSIF v_role = 'hod' THEN
        v_chain_hod := v_cur;
        EXIT;
      ELSIF v_role IN ('management', 'admin', 'superadmin') THEN
        EXIT;
      END IF;
    END IF;
    v_cur := v_next;
    i := i + 1;
  END LOOP;

  SELECT h.id INTO o_hod
  FROM profiles e JOIN profiles h ON h.id = e.hod_id
  WHERE e.id = p_profile_id AND h.role = 'hod' AND h.status = 'Active' AND h.id <> p_profile_id;
  o_hod := COALESCE(o_hod, v_chain_hod);

  -- A manager who is also the employee's HOD only approves once, as HOD.
  IF o_manager = o_hod THEN
    o_manager := NULL;
  END IF;
END;
$$;

-- Team = everyone below the caller in the manager_id tree, plus (for an
-- HOD) everyone whose hod_id is the caller and everyone below them.
CREATE OR REPLACE FUNCTION my_team_ids()
RETURNS uuid[] LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  WITH RECURSIVE tree(id, depth) AS (
    SELECT p.id, 1 FROM profiles p
    WHERE (p.manager_id = auth.uid() OR p.hod_id = auth.uid()) AND p.id <> auth.uid()
    UNION
    SELECT p.id, t.depth + 1 FROM profiles p JOIN tree t ON p.manager_id = t.id
    WHERE t.depth < 6 AND p.id <> auth.uid()
  )
  SELECT COALESCE(array_agg(DISTINCT id), '{}'::uuid[]) FROM tree;
$$;

CREATE OR REPLACE FUNCTION is_in_team_of(p_member uuid, p_leader uuid)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_cur uuid;
  i int := 0;
BEGIN
  v_cur := p_member;
  WHILE v_cur IS NOT NULL AND i < 8 LOOP
    IF EXISTS (SELECT 1 FROM profiles WHERE id = v_cur AND (manager_id = p_leader OR hod_id = p_leader)) THEN
      RETURN true;
    END IF;
    SELECT manager_id INTO v_cur FROM profiles WHERE id = v_cur;
    i := i + 1;
  END LOOP;
  RETURN false;
END;
$$;


-- ── 3. Data from HOD.xlsx ─────────────────────────────────────────────────
CREATE TEMP TABLE _sheet ON COMMIT DROP AS
SELECT * FROM
(VALUES
(2,'240','AJAY CK','AMIT SARDANA','ABHIYANT SIR'),
(3,'425','PRAVEEN KUMAR','DEEPAK DHANKAR','BHANU JAIN'),
(4,'429','AMBA DUTT','DEEPAK DHANKAR','ARZOO JAIMINY'),
(5,'367','NEERAJ KUMAR','DEEPAK DHANKAR','ARZOO JAIMINY'),
(6,'368','RASHMI KUMARI','DEEPAK DHANKAR','ARZOO JAIMINY'),
(7,'372','JASPREET SINGH','DEEPAK DHANKAR','ARZOO JAIMINY'),
(8,'377','KAMAL SINGH','DEEPAK DHANKAR','ARZOO JAIMINY'),
(9,'385','LATIKA CHAUHAN','DEEPAK DHANKAR','ARZOO JAIMINY'),
(10,'391','URVASHI BISHT','DEEPAK DHANKAR','ARZOO JAIMINY'),
(11,'392','DEEPANSHI AGARWAL','DEEPAK DHANKAR','ARZOO JAIMINY'),
(12,'395','ANKITA TIWARI','DEEPAK DHANKAR','ARZOO JAIMINY'),
(13,'409','JAISHRI DHIR','DEEPAK DHANKAR','ARZOO JAIMINY'),
(14,'438','KRITIKA DIWAKAR','DEEPAK DHANKAR','ARZOO JAIMINY'),
(15,'439','AAKASH DOLKA','DEEPAK DHANKAR','ARZOO JAIMINY'),
(16,'451','DEEPAK DHANKAR','ARZOO JAIMINY','ABHIYANT SIR'),
(17,'18','BUDHEE PRAKASH BAIRWA','MANOJ SHARMA','RAMESH YADAV'),
(18,'49','JOGENDRA SINGH','RAMESH YADAV','RAMESH YADAV'),
(19,'59','LOKENDRA BABU','MANOJ SHARMA','RAMESH YADAV'),
(20,'62','SOURAV DAS','RAMESH YADAV','RAMESH YADAV'),
(21,'65','MAHENDRA SINGH KISHNAWAT','MANOJ SHARMA','RAMESH YADAV'),
(22,'77','BABU LAL YADAV','MANOJ SHARMA','RAMESH YADAV'),
(23,'79','HARIRAM GURJAR','BUDHEE PRAKASH BAIRWA','RAMESH YADAV'),
(24,'86','ASHOK KUMAR MEHARA','SOURAV DAS','RAMESH YADAV'),
(25,'87','ASHOK SWAMI','RAMESH YADAV','RAMESH YADAV'),
(26,'95','ASHOK KUMAR SHARMA','MANOJ SHARMA','RAMESH YADAV'),
(27,'139','SHANKAR LAL','BUDHEE PRAKASH BAIRWA','RAMESH YADAV'),
(28,'150','DHARMENDRA KUMAR','BUDHEE PRAKASH BAIRWA','RAMESH YADAV'),
(29,'151','RAJENDRA KUMAR RAIGER','BUDHEE PRAKASH BAIRWA','RAMESH YADAV'),
(30,'152','RAVI KUMAR BAIRWA','BUDHEE PRAKASH BAIRWA','RAMESH YADAV'),
(31,'199','ARUN SHARMA','CHETAN GOENKA','RAMESH YADAV'),
(32,'221','SARIM KHAN','ASHOK SWAMI','RAMESH YADAV'),
(33,'271','MANISH VERMA','ASHOK SWAMI','RAMESH YADAV'),
(34,'275','VIKAS SINGH KARNAWAT','JOGENDRA SINGH','RAMESH YADAV'),
(35,'502','PARITOSH GHOSH','SANJAY RAJOWAR','RAMESH YADAV'),
(36,'506','SUROJIT DEBNATH','SANJAY RAJOWAR','RAMESH YADAV'),
(37,'508','ASHISH KUMAR PAL','JAYANTA DAS','RAMESH YADAV'),
(38,'510','HASAN SK','PALASH BARMAN','RAMESH YADAV'),
(39,'512','SUBRAT MONDAL','PALASH BARMAN','RAMESH YADAV'),
(40,'517','ASHOK KUMAR KUMAWAT','RAMESH YADAV','RAMESH YADAV'),
(41,'518','PARTHA SARDAR','MANOJ SHARMA','RAMESH YADAV'),
(42,'519','SANJAY RAJOWAR','MANOJ SHARMA','RAMESH YADAV'),
(43,'523','JAYANTA DAS','MANOJ SHARMA','RAMESH YADAV'),
(44,'526','ANIL GOTHWAL','RAHUL SAINI','RAMESH YADAV'),
(45,'531','AMIT KUMAR MONDAL','JAYANTA DAS','RAMESH YADAV'),
(46,'532','BISWAJIT ADAK','JAYANTA DAS','RAMESH YADAV'),
(47,'538','VIPLOB CHAKROBORTY','JAYANTA DAS','RAMESH YADAV'),
(48,'543','JAYANTA BARMAN','JAYANTA DAS','RAMESH YADAV'),
(49,'546','BABU SONA BARMAN','PALASH BARMAN','RAMESH YADAV'),
(50,'546','PALASH BARMAN','PALASH BARMAN','RAMESH YADAV'),
(51,'565','SHIVAM KUMAR UPRATI','PALASH BARMAN','RAMESH YADAV'),
(52,'566','GANESH DUTTA','PALASH BARMAN','RAMESH YADAV'),
(53,'571','CHANDAN RAJBHAR','JOGENDRA SINGH','RAMESH YADAV'),
(54,'573','ASHOK PAREEK','ASHOK KUMAR KUMAWAT','RAMESH YADAV'),
(55,'574','PABAN GHOSH','PALASH BARMAN','RAMESH YADAV'),
(56,'575','SAJIJUL','PALASH BARMAN','RAMESH YADAV'),
(57,'577','SUMANTA DEY','LOKENDRA BABU','RAMESH YADAV'),
(58,'579','SANJAY RAKSHIT','JAYANTA DAS','RAMESH YADAV'),
(59,'588','SUNIL KUMAR SAIN','MANOJ SHARMA','RAMESH YADAV'),
(60,'596','BAPI MONDAL','JAYANTA DAS','RAMESH YADAV'),
(61,'599','UMMED SINGH RATHOR','MANOJ SHARMA','RAMESH YADAV'),
(62,'601','POORAN RAJBHAR','JOGENDRA SINGH','RAMESH YADAV'),
(63,'607','ASIM HAZRA','PALASH BARMAN','RAMESH YADAV'),
(64,'617','SANKRITAN MONDAL','PALASH BARMAN','RAMESH YADAV'),
(65,'622','SANJAY PAL','SUNIL KUMAR SAIN','RAMESH YADAV'),
(66,'624','VIRENDRA SINGH','RAMESH YADAV','RAMESH YADAV'),
(67,'633','SWAPAN NANDI','PALASH BARMAN','RAMESH YADAV'),
(68,'637','MANOJ PAL','LOKENDRA BABU','RAMESH YADAV'),
(69,'647','PRASENJIT DAS','JAYANTA DAS','RAMESH YADAV'),
(70,'650','SANJAY VERMA','MANOJ SHARMA','RAMESH YADAV'),
(71,'651','RATAN DEY','PALASH BARMAN','RAMESH YADAV'),
(72,'657','PAPAI GHOSH','SUNIL KUMAR SAIN','RAMESH YADAV'),
(73,'661','SANJAY JANGID','JAYANTA DAS','RAMESH YADAV'),
(74,'662','MAHADEB BARMAN','SUNIL KUMAR SAIN','RAMESH YADAV'),
(75,'663','HEMANT KUMAR MAHAWAR','MANOJ SHARMA','RAMESH YADAV'),
(76,'664','RANJAN BISWAS','JAYANTA DAS','RAMESH YADAV'),
(77,'666','FARDEEN KHAN','JOGENDRA SINGH','RAMESH YADAV'),
(78,'666','SOMNATH HAZRA','JOGENDRA SINGH','RAMESH YADAV'),
(79,'666','SAURAV KUMAR','JOGENDRA SINGH','RAMESH YADAV'),
(80,'666','SANJIT MANDAL','JOGENDRA SINGH','RAMESH YADAV'),
(81,'666','SHAHZAD KHAN','JOGENDRA SINGH','RAMESH YADAV'),
(82,'669','AJAY SINGH JADAOUN','ASHOK SWAMI','RAMESH YADAV'),
(83,'670','ABHIJIT DUTTA','SUNIL KUMAR SAIN','RAMESH YADAV'),
(84,'671','CHINMOY SAHA','JAYANTA DAS','RAMESH YADAV'),
(85,'675','GAJANAND VERMA','CHETAN GOENKA','RAMESH YADAV'),
(86,'676','KISHORE KUMAR HALDAR','RAMESH YADAV','RAMESH YADAV'),
(87,'678','SHIBNATH DAS','SUNIL KUMAR SAIN','RAMESH YADAV'),
(88,'679','SARABINDU HAZRA','PALASH BARMAN','RAMESH YADAV'),
(89,'684','SUBRATA DAS','JAYANTA DAS','RAMESH YADAV'),
(90,'685','SAQIB KHAN','SHAHZAD KHAN','RAMESH YADAV'),
(91,'694','VISHNU RAJAWAT','ASHOK SWAMI','RAMESH YADAV'),
(92,'695','SUBIR','SANJAY RAJOWAR','RAMESH YADAV'),
(93,'698','SANJAY GHOSH','PALASH BARMAN','RAMESH YADAV'),
(94,'707','RAMESH KUMAR YADAV','AMIT SARDANA','RAMESH YADAV'),
(95,'709','BISWAJIT MONDAL','PALASH BARMAN','RAMESH YADAV'),
(96,'711','CHETAN GOENKA','RAMESH YADAV','RAMESH YADAV'),
(97,'711','CHETAN GOENKA','RAMESH YADAV','RAMESH YADAV'),
(98,'716','GOVIND NARAYAN SAIN','ASHOK SWAMI','RAMESH YADAV'),
(99,'718','DINESH KUMAR MEHARA','SOURAV DAS','RAMESH YADAV'),
(100,'729','INDRAJIT GHOSH','JAYANTA DAS','RAMESH YADAV'),
(101,'730','ANIL SONI','MANOJ SHARMA','RAMESH YADAV'),
(102,'731','RAHUL SAINI','MANOJ SHARMA','RAMESH YADAV'),
(103,'733','MUKESH KUMAR SHARMA','ASHOK KUMAR KUMAWAT','RAMESH YADAV'),
(104,'738','SUKANTA BISWAS','JAYANTA DAS','RAMESH YADAV'),
(105,'739','KISHORE HALDER','JAYANTA DAS','RAMESH YADAV'),
(106,'740','MANOJ KUMAR SHARMA','RAMESH YADAV','RAMESH YADAV'),
(107,'741','PATIRAM MONDAL','SANJAY RAJOWAR','RAMESH YADAV'),
(108,'749','ROHIT SAINI','CHETAN GOENKA','RAMESH YADAV'),
(109,'752','ARIF KHAN','SHAHZAD KHAN','RAMESH YADAV'),
(110,'756','PURUSHOTAM BAIRWA','BUDHEE PRAKASH BAIRWA','RAMESH YADAV'),
(111,'766','DIPAK HALDER','SOURAV DAS','RAMESH YADAV'),
(112,'768','TOTAN MONDAL','SUNIL KUMAR SAIN','RAMESH YADAV'),
(113,'770','RAJ DAS','SUNIL KUMAR SAIN','RAMESH YADAV'),
(114,'771','SINTU DEY','SANJAY RAJOWAR','RAMESH YADAV'),
(115,'772','KISHAN SONI','ASHOK KUMAR KUMAWAT','RAMESH YADAV'),
(116,'774','WASIM AKTAR','PALASH BARMAN','RAMESH YADAV'),
(117,'776','UMANG GUPTA','MANOJ SHARMA','RAMESH YADAV'),
(118,'777','RAVI SAINI','MANOJ SHARMA','RAMESH YADAV'),
(119,'778','LAKHAN MURMU','HEMANT KUMAR MAHAWAR','RAMESH YADAV'),
(120,'779','CHANDAN SINGH','ASHOK SWAMI','RAMESH YADAV'),
(121,'780','AJAY KUMAR PANCHAL','ASHOK SWAMI','RAMESH YADAV'),
(122,'781','RAKESH DEY','PALASH BARMAN','RAMESH YADAV'),
(123,'782','BANTI MEENA','PALASH BARMAN','RAMESH YADAV'),
(124,'783','GOBINDO HAZRA','PALASH BARMAN','RAMESH YADAV'),
(125,'784','BHUBAN DEY','PALASH BARMAN','RAMESH YADAV'),
(126,'785','KUMAR MITRA','PALASH BARMAN','RAMESH YADAV'),
(127,'786','BISHNU GHOSH','SOURAV DAS','RAMESH YADAV'),
(128,'787','RANJIT BISWAS','MANOJ SHARMA','RAMESH YADAV'),
(129,'788','ANIL KUMAR BAIRWA','HEMANT KUMAR MAHAWAR','RAMESH YADAV'),
(130,'789','DEEPAK KUMAR BAIRWA','RAHUL SAINI','RAMESH YADAV'),
(131,'','AANAND CONTRACT','SUNIL SONI','RAMESH YADAV'),
(132,'','KOSIK CONTRACT','SUNIL SONI','RAMESH YADAV'),
(133,'','MANISH CONTRACT','SUNIL SONI','RAMESH YADAV'),
(134,'','SONU CONTRACT','SUNIL SONI','RAMESH YADAV'),
(135,'82','MEHUL CHANDULAL VITHLANI','AMIT SARDANA','ABHIYANT SIR'),
(136,'460','FARHEEN SAIFI','PAWAN SHARMA','ARZOO JAIMINY'),
(137,'461','PAWAN SHARMA','MANISH MISHRA','ARZOO JAIMINY'),
(138,'200','PAVAN LONE','RAHUL SETHIA','AMIT SARDANA'),
(139,'302','RAHUL SETHIA','AMIT SARDANA','ABHIYANT SIR'),
(140,'435','YASH VERMA','RAHUL SETHIA','AMIT SARDANA'),
(141,'81','AMEY PALAV','AMIT SARDANA','ABHIYANT SIR'),
(142,'442','AFZAL ANWAR SHEIKH','AMEY PALAV','AMIT SARDANA'),
(143,'444','SAJEEV THANKAPPAN KAZHANCHI','AMIT SARDANA','ABHIYANT SIR'),
(144,'94','NARENDRA ASNANI','AMIT SARDANA','ABHIYANT SIR'),
(145,'394','RITIK JAIN','AMIT SARDANA','ABHIYANT SIR'),
(146,'253','ARZOO JAIMINY','ABHISHEK SIR','ABHISHEK SIR'),
(147,'1','GUNJAN SHARMA','ABHISHEK SIR','ABHISHEK SIR'),
(148,'2','GANESH CHAND SHARMA','ABHISHEK SIR','ABHISHEK SIR'),
(149,'3','RAJESH JAIN','GANESH SHARMA','ABHISHEK SIR'),
(150,'7','MOHAN LAL SHARMA','GUNJAN SHARMA','ABHISHEK SIR'),
(151,'14','PUSHPA JHA','ABHISHEK SIR','ABHISHEK SIR'),
(152,'15','KANHAIYA LAL KUMAWAT','ABHISHEK SIR','ABHISHEK SIR'),
(153,'21','MUKESH KUMAR CHOUDHARY','GUNJAN SHARMA','ABHISHEK SIR'),
(154,'25','MOHIT PAREEK','ABHISHEK SIR','ABHISHEK SIR'),
(155,'56','MONIKA KASUMBHIWAL','BHANU JAIN','ABHISHEK SIR'),
(156,'60','AMIT SARDANA','ABHISHEK SIR','ABHIYANT SIR'),
(157,'64','PUSHPENDRA SINGH RAJPUT','ABHISHEK SIR','ABHISHEK SIR'),
(158,'71','SHREEJA MAHASANI','ARZOO JAIMINY','ABHIYANT SIR'),
(159,'74','TARUN SHARMA','AMIT SARDANA','ABHIYANT SIR'),
(160,'78','ANUJ PAREEK','BHANWAR SINGH','AMIT SARDANA'),
(161,'113','NARENDRA GAUTAM','BHANU JAIN','ABHISHEK SIR'),
(162,'115','SHANKAR LAL PARASHAR','BHANU JAIN','ABHISHEK SIR'),
(163,'125','BHANU JAIN','ABHISHEK SIR','ABHISHEK SIR'),
(164,'132','GAURAV KESHWANI','ABHISHEK SIR','ABHISHEK SIR'),
(165,'138','SHIPRA SRIVASTAVA','SHREEJA MAHASANI','ARZOO JAIMINY'),
(166,'144','JAIDEEP MEHRA','PUSHPA JHA','PUSHPA JHA'),
(167,'156','GYAN CHAND PALIWAL','DIVYA BAID','ABHISHEK SIR'),
(168,'163','RAM KISHORE SHARMA','AMIT SARDANA','ABHIYANT SIR'),
(169,'165','BOSKY SHARMA','ABHISHEK SIR','ABHISHEK SIR'),
(170,'169','KUSHAGRA SINGH','GUNJAN SHARMA','ABHISHEK SIR'),
(171,'171','SUMIT CHANGIL','SHREEJA MAHASANI','ARZOO JAIMINY'),
(172,'184','VIKAS SINGH','AMIT SARDANA','AMIT SARDANA'),
(173,'187','SIDDHARTH AJMERA','AMIT SARDANA','ABHISHEK SIR'),
(174,'192','LOKESH SAHU','AMIT SARDANA','ABHIYANT SIR'),
(175,'194','BHANWAR SINGH SHEKHAWAT','AMIT SARDANA','ABHIYANT SIR'),
(176,'201','UMA SONI','ABHISHEK SIR','ABHISHEK SIR'),
(177,'206','SUHAIL TARIQ','UMA SONI','ABHISHEK SIR'),
(178,'208','AJAY CHOMAL','BHANU JAIN','ABHISHEK SIR'),
(179,'210','JITENDRA KUMAR SHARMA','AMIT SARDANA','ABHISHEK SIR'),
(180,'214','TOFFIK KHAN','ARZOO JAIMINY','ABHISHEK SIR'),
(181,'216','DILEEP SINGH','GUNJAN SHARMA','ABHISHEK SIR'),
(182,'220','BHAVNA SHARMA','SHREEJA MAHASANI','ARZOO JAIMINY'),
(183,'223','HARSH PALIWAL','ARZOO JAIMINY','ABHISHEK SIR'),
(184,'228','PRASHANT SINGH GAUR','GUNJAN SHARMA','ABHISHEK SIR'),
(185,'230','PUJA KUMARI','UMA SONI','ABHISHEK SIR'),
(186,'232','RAM JEEVAN MEENA','PUSHPA JHA','PUSHPA JHA'),
(187,'237','YOGENDRA SINGH CHOUHAN','PUSHPA JHA','PUSHPA JHA'),
(188,'241','LOKESH BAIRWA','PUSHPENDRA SINGH','PUSHPENDRA SINGH'),
(189,'242','NITESH TIWARI','ABHISHEK SIR','ABHISHEK SIR'),
(190,'245','MANOJ KUMAR','KANHAIYA LAL KUMAWAT','ABHISHEK SIR'),
(191,'249','ABHINAV SINGH','ARPITA JAIN','ABHISHEK SIR'),
(192,'255','RAKSHITA JAIN','RAHUL TRIVEDI','AMIT SARDANA'),
(193,'259','MUKESH SHARMA','KANHAIYA LAL KUMAWAT','ABHISHEK SIR'),
(194,'261','RADHE SHYAM SHARMA','ARZOO JAIMINY','ABHISHEK SIR'),
(195,'262','NEHA SONI','BHUMIKA SHARMA','ARZOO JAIMINY'),
(196,'267','DOLLY SHARMA','GUNJAN SHARMA','ABHISHEK SIR'),
(197,'268','MAHAK PARVEEN','GAURAV KESHWANI','AMIT SARDANA'),
(198,'280','DEEPAK CHOUDHARY','AMIT SARDANA','AMIT SARDANA'),
(199,'282','KHUSHBOO MEENA','SHREEJA MAHASANI','ARZOO JAIMINY'),
(200,'286','SEEMA JANGID','AMIT SARDANA','ABHIYANT SIR'),
(201,'291','RAHUL TRIVEDI','AMIT SARDANA','ABHIYANT SIR'),
(202,'298','YUKTI SONI','UMA SONI','ABHISHEK SIR'),
(203,'300','RAJUL JAIN','ARZOO JAIMINY','ABHISHEK SIR'),
(204,'305','EKTA RATHORE','RAHUL TRIVEDI','AMIT SARDANA'),
(205,'306','PUSHPENDRA VERMA','RAHUL TRIVEDI','AMIT SARDANA'),
(206,'310','DIVYA ASWANI','SHREEJA MAHASANI','ARZOO JAIMINY'),
(207,'316','YUVRAJ SINGH','DIVYA BAID','ABHISHEK SIR'),
(208,'319','RIYA YADAV','RAHUL TRIVEDI','AMIT SARDANA'),
(209,'320','SUNIL KUMAR BAIRWA','AMIT SARDANA','AMIT SARDANA'),
(210,'327','DIVYA BAID','ABHISHEK SIR','ABHISHEK SIR'),
(211,'330','PRAGATI TIWARI','AMIT SARDANA','ABHIYANT SIR'),
(212,'332','REKHA LAXKAR','UMA SONI','ABHISHEK SIR'),
(213,'336','ABHISHEK KUMAR SONI','RAHUL TRIVEDI','AMIT SARDANA'),
(214,'339','PRATIBHA VASHISHTHA','IMRAN KHAN','ABHISHEK SIR'),
(215,'343','BHUMIKA SHARMA','ARZOO JAIMINY','ABHISHEK SIR'),
(216,'346','SHRWAN KUMAR SONI','AMIT SARDANA','AMIT SARDANA'),
(217,'350','VINAYAK HARIT','AMIT SARDANA','ABHIYANT SIR'),
(218,'352','SHRI KRISHAN SHARMA','DIVYA BAID','ABHISHEK SIR'),
(219,'353','PRINCY TANK','BHUMIKA SHARMA','ARZOO JAIMINY'),
(220,'356','IMRAN NASIR KHAN','ABHISHEK SIR','ABHISHEK SIR'),
(221,'357','POOJA KHANDELWAL','ABHISHEK SIR','ABHISHEK SIR'),
(222,'360','BHAVYA GARG','ARZOO JAIMINY','ABHISHEK SIR'),
(223,'363','MUKESH SINGH','GUNJAN SHARMA','ABHISHEK SIR'),
(224,'364','POONAM BHAT','SHREEJA MAHASANI','ARZOO JAIMINY'),
(225,'365','HIMANSHI','POOJA KHANDELWAL','POOJA KHANDELWAL'),
(226,'373','VISHAL YADAV','DIVYA BAID','ABHISHEK SIR'),
(227,'374','VASUNDHARA SHARMA','AMIT SARDANA','ABHIYANT SIR'),
(228,'384','KAPIL KUMAR VERMA','AMIT SARDANA','ABHISHEK SIR'),
(229,'386','SURESH CHAND KUMAWAT','PUSHPA JHA','PUSHPA JHA'),
(230,'388','NIKITA PARMANI','SHREEJA MAHASANI','ARZOO JAIMINY'),
(231,'398','LIZA THAKWANI','ARPITA JAIN','ABHISHEK SIR'),
(232,'401','AMAN BISWAS','RAHUL SETHIA','AMIT SARDANA'),
(233,'402','RAVI KUMAR','ARZOO JAIMINY','ABHISHEK SIR'),
(234,'406','LALLU RAM','RAHUL TRIVEDI','AMIT SARDANA'),
(235,'408','AYUSH AGARWAL','ARPITA JAIN','ABHISHEK SIR'),
(236,'413','GUNGUN AGARWAL','BHUMIKA SHARMA','ARZOO JAIMINY'),
(237,'414','SAGAR BHATIA','RADHE SHYAM SHARMA','ARZOO JAIMINY'),
(238,'415','MANISH MISHRA','ARZOO JAIMINY','ABHIYANT SIR'),
(239,'417','DEEPAK KUMAR','PRATIBHA VASHISHTA','ARZOO JAIMINY'),
(240,'418','VARSHA SONI','ARZOO JAIMINY','ABHISHEK SIR'),
(241,'420','LALIT SAINI','RAHUL TRIVEDI','AMIT SARDANA'),
(242,'421','GAYATRI KUMAWAT','ARZOO JAIMINY','ABHIYANT SIR'),
(243,'424','RAHUL VERMA','SIDDHARTH AJMERA','AMIT SARDANA'),
(244,'430','AJAY SINGH SHEKHAWAT','POOJA KHANDELWAL','POOJA KHANDELWAL'),
(245,'433','GAJENDRA KUMAWAT','PUSHPA JHA','PUSHPA JHA'),
(246,'437','TARUN PRAJAPAT','ARZOO JAIMINY','ABHISHEK SIR'),
(247,'440','NAMAN KHANDELWAL','NITESH TIWARI','ABHISHEK SIR'),
(248,'441','GEETA SINGH','IMRAN KHAN','ABHISHEK SIR'),
(249,'443','AMISHI VIJAY','PRATIBHA VASHISHTA','ARZOO JAIMINY'),
(250,'446','NIHARIKA JAMAR','ARZOO JAIMINY','ABHISHEK SIR'),
(251,'447','VARUN GANGAWAT','ARZOO JAIMINY','ABHISHEK SIR'),
(252,'448','DEVIKA SATHEESH K','IMRAN KHAN','ARZOO JAIMINY'),
(253,'450','VANSHIKA GAUR','POOJA KHANDELWAL','POOJA KHANDELWAL'),
(254,'452','JITENDRA JATAV','PUSHPA JHA','PUSHPA JHA'),
(255,'453','RISHAB CHAUDHARY','POOJA KHANDELWAL','POOJA KHANDELWAL'),
(256,'454','PANKAJ DAS','IMRAN KHAN','AMIT SARDANA'),
(257,'455','KANISHK AGARWAL','KANHAIYA LAL KUMAWAT','ABHISHEK SIR'),
(258,'457','ASTHA TIBREWAL','ARZOO JAIMINY','ABHISHEK SIR'),
(259,'458','RISHITA BALDOTA','IMRAN KHAN','ABHISHEK SIR'),
(260,'459','MOHIT KUMAR JANGID','BHANU JAIN','ABHISHEK SIR'),
(261,'462','RAHUL JANGID','ARPITA JAIN','ABHISHEK SIR'),
(262,'539','RAHUL KUMAWAT','AMIT SARDANA','AMIT SARDANA'),
(263,'449','DHAVAL BHAVESHKUMAR TRIVEDI','MEHUL VITHLANI','AMIT SARDANA')
) AS s(xl_row, code, name, mgr, hod);

-- HR-confirmed aliases for MANAGER/HOD names that differ from CrewCore.
CREATE TEMP TABLE _alias ON COMMIT DROP AS
SELECT * FROM (VALUES
  ('RAMESH YADAV', '707'), ('MANOJ SHARMA', '740'), ('IMRAN KHAN', '356'), ('GANESH SHARMA', '2'),
  ('MEHUL VITHLANI', '82'), ('PRATIBHA VASHISHTA', '339'), ('BHANWAR SINGH', '194'), ('PUSHPENDRA SINGH', '64')
) AS a(name, code);

-- Name-to-name aliases (profile renamed / duplicate inactive record).
CREATE TEMP TABLE _name_alias ON COMMIT DROP AS
SELECT * FROM (VALUES ('PALASH BARMAN', 'POLASH BARMAN')) AS a(name, db_name);

CREATE TEMP TABLE _p ON COMMIT DROP AS
SELECT p.id, p.employee_id, p.role, p.status,
       upper(regexp_replace(trim(concat_ws(' ', p.first_name, p.middle_name, p.last_name)), '\s+', ' ', 'g')) AS nm
FROM profiles p JOIN tenants t ON t.id = p.tenant_id
WHERE t.company_name ILIKE '%Raniwala%';

-- Sheet row -> profile: code (name must agree only when the sheet reuses
-- that code for several people), else unique exact name.
CREATE TEMP TABLE _emp ON COMMIT DROP AS
SELECT s.xl_row, s.name, s.mgr, s.hod,
       COALESCE(
         (SELECT p.id FROM _p p WHERE s.code <> '' AND p.employee_id = s.code
            AND (p.nm = s.name OR p.nm LIKE s.name || ' %'
                 OR (SELECT count(DISTINCT x.name) FROM _sheet x WHERE x.code = s.code) = 1) LIMIT 1),
         (SELECT min(p.id::text)::uuid FROM _p p WHERE p.nm = s.name HAVING count(*) = 1)
       ) AS pid
FROM _sheet s;

-- Leader name -> profile: alias code, else that person's own sheet row,
-- else a unique exact name.
CREATE TEMP TABLE _leader ON COMMIT DROP AS
SELECT l.name,
       COALESCE(
         (SELECT p.id FROM _alias a JOIN _p p ON p.employee_id = a.code WHERE a.name = l.name LIMIT 1),
         (SELECT p.id FROM _name_alias a JOIN _p p ON p.nm = a.db_name AND p.status = 'Active' WHERE a.name = l.name LIMIT 1),
         (SELECT e.pid FROM _emp e WHERE e.name = l.name AND e.pid IS NOT NULL LIMIT 1),
         (SELECT min(p.id::text)::uuid FROM _p p WHERE p.nm = l.name HAVING count(*) = 1)
       ) AS pid
FROM (SELECT mgr AS name FROM _sheet UNION SELECT hod FROM _sheet) l;

-- Roles: HODs first, then managers (never demote HR, never touch Inactive).
UPDATE profiles p SET role = 'hod'
FROM _leader l
WHERE p.id = l.pid AND l.name IN (SELECT hod FROM _sheet)
  AND p.role IN ('employee', 'manager') AND p.status = 'Active';

UPDATE profiles p SET role = 'manager'
FROM _leader l
WHERE p.id = l.pid AND l.name IN (SELECT mgr FROM _sheet)
  AND p.role = 'employee' AND p.status = 'Active';

-- Explicit HOD per employee (manager_id is left as 20260926_7 set it).
UPDATE profiles p
SET hod_id = CASE WHEN lh.pid = e.pid THEN NULL
                  WHEN (SELECT role FROM profiles WHERE id = lh.pid) = 'hod' THEN lh.pid END
FROM _emp e
LEFT JOIN _leader lh ON lh.name = e.hod
WHERE p.id = e.pid;

NOTIFY pgrst, 'reload schema';
