-- =============================================================
-- Raniwala Jewellers -- align employee name / department / division with
-- HR's master spreadsheet ("Employee Master for attendance.xlsx"),
-- matched by ESSL employee code (profiles.essl_employee_code), which is
-- the biometric-device code and matches the sheet's "EMP CODE" column
-- exactly (both are small sequential integers, unlike profiles.employee_id
-- which is a separate HR-assigned alphanumeric code).
--
-- Scope: ONLY profiles whose essl_employee_code matches a row in the sheet
-- below are touched. Any Raniwala employee not in the sheet (e.g. essl
-- codes 109/135 seen as "Umesh User"/"Pratik User" placeholder accounts)
-- is left completely alone -- name, department, division untouched.
--
-- EXCLUDED for data-quality reasons -- these EMP CODEs are reused for
-- MULTIPLE different names in the sheet itself (ambiguous, can't safely
-- match to one profile) -- flag to HR to fix the source sheet:
--   546 -> BABU SONA BARMAN / PALASH BARMAN
--   666 -> FARDEEN KHAN / SOMNATH HAZRA / SAURAV KUMAR / SANJIT MANDAL / SHAHZAD KHAN
--   711 -> CHETAN GOENKA (listed twice, harmless duplicate, still excluded out of caution)
--
-- Division is only overwritten when the sheet has a non-blank value for
-- that row (2 rows -- EMP CODE 138, 171 -- have a blank DIVISION in the
-- sheet; their existing division is left as-is rather than being cleared).
--
-- attendance/punches/leave history is never touched -- this migration only
-- updates profiles.first_name/middle_name/last_name/department/division.
-- =============================================================

DO $$
DECLARE
  v_tenant_id uuid;
  v_matched int;
BEGIN
  SELECT id INTO v_tenant_id FROM tenants WHERE company_name ILIKE '%Raniwala%' LIMIT 1;
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'Raniwala Jewellers tenant not found';
  END IF;

  CREATE TEMP TABLE _raniwala_master (
    emp_code text, first_name text, middle_name text, last_name text, department text, division text
  ) ON COMMIT DROP;

  INSERT INTO _raniwala_master (emp_code, first_name, middle_name, last_name, department, division) VALUES
    ('1', 'GUNJAN', '', 'SHARMA', 'ADMIN', 'SUPPORT'),
    ('2', 'GANESH', 'CHAND', 'SHARMA', 'ACCOUNTS', 'SUPPORT'),
    ('3', 'RAJESH', '', 'JAIN', 'ACCOUNTS', 'SUPPORT'),
    ('7', 'MOHAN', 'LAL', 'SHARMA', 'ADMIN', 'SUPPORT'),
    ('14', 'PUSHPA', '', 'JHA', 'STOCK', 'SUPPORT'),
    ('15', 'KANHAIYA', 'LAL', 'KUMAWAT', 'ACCOUNTS', 'SUPPORT'),
    ('18', 'BUDHEE', 'PRAKASH', 'BAIRWA', 'PUWAI', 'FACTORY'),
    ('21', 'MUKESH', 'KUMAR', 'CHOUDHARY', 'ADMIN', 'SUPPORT'),
    ('25', 'MOHIT', '', 'PAREEK', 'PURCHASE', 'SUPPORT'),
    ('49', 'JOGENDRA', '', 'SINGH', 'DIAMOND ASSORTING', 'FACTORY'),
    ('56', 'MONIKA', '', 'KASUMBHIWAL', 'ACCOUNTS', 'SUPPORT'),
    ('59', 'LOKENDRA', '', 'BABU', 'BAGGING', 'FACTORY'),
    ('60', 'AMIT', '', 'SARDANA', 'B2B', 'B2B'),
    ('62', 'SOURAV', '', 'DAS', 'CAD', 'FACTORY'),
    ('64', 'PUSHPENDRA', 'SINGH', 'RAJPUT', 'IT', 'SUPPORT'),
    ('65', 'MAHENDRA', 'SINGH', 'KISHNAWAT', 'DIAMOND BAGGING', 'FACTORY'),
    ('71', 'SHREEJA', '', 'MAHASANI', 'B2C', 'B2C'),
    ('74', 'TARUN', '', 'SHARMA', 'B2B', 'B2B'),
    ('77', 'BABU', 'LAL', 'YADAV', 'CAMING', 'FACTORY'),
    ('78', 'ANUJ', '', 'PAREEK', 'B2B- STOCK', 'B2B'),
    ('79', 'HARIRAM', '', 'GURJAR', 'PUWAI', 'FACTORY'),
    ('81', 'AMEY', '', 'PALAV', 'B2B', 'B2B'),
    ('82', 'MEHUL', 'CHANDULAL', 'VITHLANI', 'B2B', 'B2B'),
    ('86', 'ASHOK', 'KUMAR', 'MEHARA', 'CAD', 'FACTORY'),
    ('87', 'ASHOK', '', 'SWAMI', 'PRODUCTION', 'FACTORY'),
    ('94', 'NARENDRA', '', 'ASNANI', 'B2B', 'B2B'),
    ('95', 'ASHOK', 'KUMAR', 'SHARMA', 'DIAMOND BAGGING', 'FACTORY'),
    ('113', 'NARENDRA', '', 'GAUTAM', 'ACCOUNTS', 'SUPPORT'),
    ('115', 'SHANKAR', 'LAL', 'PARASHAR', 'ACCOUNTS', 'SUPPORT'),
    ('125', 'BHANU', '', 'JAIN', 'ACCOUNTS', 'SUPPORT'),
    ('132', 'GAURAV', '', 'KESHWANI', 'MDO', 'SUPPORT'),
    ('138', 'SHIPRA', '', 'SRIVASTAVA', 'B2C', ''),
    ('139', 'SHANKAR', '', 'LAL', 'PUWAI', 'FACTORY'),
    ('144', 'JAIDEEP', '', 'MEHRA', 'STOCK', 'SUPPORT'),
    ('150', 'DHARMENDRA', '', 'KUMAR', 'PUWAI', 'FACTORY'),
    ('151', 'RAJENDRA', 'KUMAR', 'RAIGER', 'PUWAI', 'FACTORY'),
    ('152', 'RAVI', 'KUMAR', 'BAIRWA', 'PUWAI', 'FACTORY'),
    ('156', 'GYAN', 'CHAND', 'PALIWAL', 'PURCHASE', 'SUPPORT'),
    ('163', 'RAM', 'KISHORE', 'SHARMA', 'B2B-CRM', 'B2B'),
    ('165', 'BOSKY', '', 'SHARMA', 'MDO', 'SUPPORT'),
    ('169', 'KUSHAGRA', '', 'SINGH', 'ADMIN', 'SUPPORT'),
    ('171', 'SUMIT', '', 'CHANGIL', 'B2C', ''),
    ('184', 'VIKAS', '', 'SINGH', 'QUALITY CONTROL', 'B2B'),
    ('187', 'SIDDHARTH', '', 'AJMERA', 'MDO', 'MDO'),
    ('192', 'LOKESH', '', 'SAHU', 'B2B-CRM', 'B2B'),
    ('194', 'BHANWAR', 'SINGH', 'SHEKHAWAT', 'B2B- STOCK', 'B2B'),
    ('199', 'ARUN', '', 'SHARMA', 'PPC', 'FACTORY'),
    ('200', 'PAVAN', '', 'LONE', 'B2B', 'B2B'),
    ('201', 'UMA', '', 'SONI', 'DESIGNING', 'SUPPORT'),
    ('206', 'SUHAIL', '', 'TARIQ', 'DESIGNING', 'SUPPORT'),
    ('208', 'AJAY', '', 'CHOMAL', 'ACCOUNTS', 'SUPPORT'),
    ('210', 'JITENDRA', 'KUMAR', 'SHARMA', 'MDO', 'MDO'),
    ('214', 'TOFFIK', '', 'KHAN', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('216', 'DILEEP', '', 'SINGH', 'ADMIN', 'SUPPORT'),
    ('220', 'BHAVNA', '', 'SHARMA', 'B2C', 'B2C'),
    ('221', 'SARIM', '', 'KHAN', 'DIAMOND BAGGING', 'FACTORY'),
    ('223', 'HARSH', '', 'PALIWAL', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('228', 'PRASHANT', 'SINGH', 'GAUR', 'ADMIN', 'SUPPORT'),
    ('230', 'PUJA', '', 'KUMARI', 'DESIGNING', 'SUPPORT'),
    ('232', 'RAM', 'JEEVAN', 'MEENA', 'STOCK', 'SUPPORT'),
    ('237', 'YOGENDRA', 'SINGH', 'CHOUHAN', 'STOCK', 'SUPPORT'),
    ('240', 'AJAY', '', 'CK', 'B2B', 'B2B'),
    ('241', 'LOKESH', '', 'BAIRWA', 'IT', 'SUPPORT'),
    ('242', 'NITESH', '', 'TIWARI', 'PURCHASE', 'SUPPORT'),
    ('245', 'MANOJ', '', 'KUMAR', 'ACCOUNTS', 'SUPPORT'),
    ('249', 'ABHINAV', '', 'SINGH', 'ACCOUNTS', 'SUPPORT'),
    ('253', 'ARZOO', '', 'JAIMINY', 'RETAIL & ECOM', 'B2C'),
    ('255', 'RAKSHITA', '', 'JAIN', 'B2B-CRM', 'B2B'),
    ('259', 'MUKESH', '', 'SHARMA', 'ACCOUNTS', 'SUPPORT'),
    ('261', 'RADHE', 'SHYAM', 'SHARMA', 'DIGITAL MARKETING', 'B2C'),
    ('262', 'NEHA', '', 'SONI', 'ECOM', 'B2C'),
    ('267', 'DOLLY', '', 'SHARMA', 'ADMIN', 'SUPPORT'),
    ('268', 'MAHAK', '', 'PARVEEN', 'MDO', 'SUPPORT'),
    ('271', 'MANISH', '', 'VERMA', 'POLKI BAGGING', 'FACTORY'),
    ('275', 'VIKAS', 'SINGH', 'KARNAWAT', 'DIAMOND ASSORTING', 'FACTORY'),
    ('280', 'DEEPAK', '', 'CHOUDHARY', 'QUALITY CONTROL', 'SUPPORT'),
    ('282', 'KHUSHBOO', '', 'MEENA', 'B2C', 'B2C'),
    ('286', 'SEEMA', '', 'JANGID', 'B2B-CRM', 'B2B'),
    ('291', 'RAHUL', '', 'TRIVEDI', 'B2B-CRM', 'B2B'),
    ('298', 'YUKTI', '', 'SONI', 'DESIGNING', 'SUPPORT'),
    ('300', 'RAJUL', '', 'JAIN', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('302', 'RAHUL', '', 'SETHIA', 'B2B', 'B2B'),
    ('305', 'EKTA', '', 'RATHORE', 'B2B-CRM', 'B2B'),
    ('306', 'PUSHPENDRA', '', 'VERMA', 'B2B-CRM', 'B2B'),
    ('310', 'DIVYA', '', 'ASWANI', 'B2C', 'B2C'),
    ('316', 'YUVRAJ', '', 'SINGH', 'PURCHASE', 'SUPPORT'),
    ('319', 'RIYA', '', 'YADAV', 'B2B-CRM', 'B2B'),
    ('320', 'SUNIL', 'KUMAR', 'BAIRWA', 'PUWAI', 'SUPPORT'),
    ('327', 'DIVYA', '', 'BAID', 'PURCHASE', 'SUPPORT'),
    ('330', 'PRAGATI', '', 'TIWARI', 'B2B-CRM', 'B2B'),
    ('332', 'REKHA', '', 'LAXKAR', 'DESIGNING', 'SUPPORT'),
    ('336', 'ABHISHEK', 'KUMAR', 'SONI', 'B2B-CRM', 'B2B'),
    ('339', 'PRATIBHA', '', 'VASHISHTHA', 'MERCHANDISING', 'SUPPORT'),
    ('343', 'BHUMIKA', '', 'SHARMA', 'ECOM', 'B2C'),
    ('346', 'SHRWAN', 'KUMAR', 'SONI', 'QUALITY CONTROL', 'SUPPORT'),
    ('350', 'VINAYAK', '', 'HARIT', 'B2B', 'B2B'),
    ('352', 'SHRI', 'KRISHAN', 'SHARMA', 'PURCHASE', 'SUPPORT'),
    ('353', 'PRINCY', '', 'TANK', 'ECOM', 'B2C'),
    ('356', 'IMRAN', 'NASIR', 'KHAN', 'MERCHANDISING', 'SUPPORT'),
    ('357', 'POOJA', '', 'KHANDELWAL', 'HR', 'SUPPORT'),
    ('360', 'BHAVYA', '', 'GARG', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('363', 'MUKESH', '', 'SINGH', 'ADMIN', 'SUPPORT'),
    ('364', 'POONAM', '', 'BHAT', 'B2C', 'B2C'),
    ('365', 'HIMANSHI', '', '', 'HR', 'SUPPORT'),
    ('367', 'NEERAJ', '', 'KUMAR', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('368', 'RASHMI', '', 'KUMARI', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('372', 'JASPREET', '', 'SINGH', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('373', 'VISHAL', '', 'YADAV', 'PURCHASE', 'SUPPORT'),
    ('374', 'VASUNDHARA', '', 'SHARMA', 'B2B', 'B2B'),
    ('377', 'KAMAL', '', 'SINGH', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('384', 'KAPIL', 'KUMAR', 'VERMA', 'QUALITY CONTROL', 'SUPPORT'),
    ('385', 'LATIKA', '', 'CHAUHAN', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('386', 'SURESH', 'CHAND', 'KUMAWAT', 'STOCK', 'SUPPORT'),
    ('388', 'NIKITA', '', 'PARMANI', 'B2C', 'B2C'),
    ('391', 'URVASHI', '', 'BISHT', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('392', 'DEEPANSHI', '', 'AGARWAL', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('394', 'RITIK', '', 'JAIN', 'B2B', 'B2B'),
    ('395', 'ANKITA', '', 'TIWARI', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('398', 'LIZA', '', 'THAKWANI', 'B2C', 'B2C'),
    ('401', 'AMAN', '', 'BISWAS', 'B2B-CRM', 'B2B'),
    ('402', 'RAVI', '', 'KUMAR', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('406', 'LALLU', '', 'RAM', 'B2B- ADMIN', 'B2B'),
    ('408', 'AYUSH', '', 'AGARWAL', 'MIS', 'SUPPORT'),
    ('409', 'JAISHRI', '', 'DHIR', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('413', 'GUNGUN', '', 'AGARWAL', 'ECOM', 'B2C'),
    ('414', 'SAGAR', '', 'BHATIA', 'DIGITAL MARKETING', 'B2C'),
    ('415', 'MANISH', '', 'MISHRA', 'B2C', 'B2C'),
    ('416', 'NIKITA', '', 'GROVER', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('417', 'DEEPAK', '', 'KUMAR', 'MERCHANDISING', 'SUPPORT'),
    ('418', 'VARSHA', '', 'SONI', 'ECOM', 'B2C'),
    ('420', 'LALIT', '', 'SAINI', 'B2B-CRM', 'B2B'),
    ('421', 'GAYATRI', '', 'KUMAWAT', 'B2C', 'B2C'),
    ('424', 'RAHUL', '', 'VERMA', 'MDO', 'SUPPORT'),
    ('425', 'PRAVEEN', '', 'KUMAR', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('426', 'RIDDHIMA', '', 'GAUR', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('429', 'AMBA', '', 'DUTT', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('430', 'AJAY', 'SINGH', 'SHEKHAWAT', 'HR', 'SUPPORT'),
    ('433', 'GAJENDRA', '', 'KUMAWAT', 'STOCK', 'SUPPORT'),
    ('435', 'YASH', '', 'VERMA', 'B2B', 'B2B'),
    ('437', 'TARUN', '', 'PRAJAPAT', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('438', 'KRITIKA', '', 'DIWAKAR', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('439', 'AAKASH', '', 'DOLKA', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('440', 'NAMAN', '', 'KHANDELWAL', 'STOCK', 'SUPPORT'),
    ('441', 'GEETA', '', 'SINGH', 'MERCHANDISING', 'SUPPORT'),
    ('442', 'AFZAL', 'ANWAR', 'SHEIKH', 'B2B', 'B2B'),
    ('443', 'AMISHI', '', 'VIJAY', 'E-COMMERCE', 'B2C'),
    ('444', 'SAJEEV', 'THANKAPPAN', 'KAZHANCHI', 'B2B', 'B2B'),
    ('446', 'NIHARIKA', '', 'JAMAR', 'MARKETING', 'B2C'),
    ('447', 'VARUN', '', 'GANGAWAT', 'SOCIAL MEDIA MARKETING', 'B2C'),
    ('448', 'DEVIKA', 'SATHEESH', 'K', 'MERCHANDISING', 'SUPPORT'),
    ('449', 'DHAVAL', 'BHAVESHKUMAR', 'TRIVEDI', 'B2B', 'B2B'),
    ('450', 'VANSHIKA', '', 'GAUR', 'HR', 'SUPPORT'),
    ('451', 'DEEPAK', '', 'DHANKAR', 'B2C (DELHI)', 'B2C (DELHI)'),
    ('452', 'JITENDRA', '', 'JATAV', 'STOCK', 'SUPPORT'),
    ('453', 'RISHAB', '', 'CHAUDHARY', 'HR', 'SUPPORT'),
    ('454', 'PANKAJ', '', 'DAS', 'MERCHANDISING', 'SUPPORT'),
    ('455', 'KANISHK', '', 'AGARWAL', 'ACCOUNTS', 'SUPPORT'),
    ('457', 'ASTHA', '', 'TIBREWAL', 'SOCIAL MEDIA & MARKETING', 'B2C'),
    ('458', 'RISHITA', '', 'BALDOTA', 'MERCHANDISING', 'SUPPORT'),
    ('459', 'MOHIT', 'KUMAR', 'JANGID', 'ACCOUNTS', 'SUPPORT'),
    ('460', 'FARHEEN', '', 'SAIFI', 'B2C', 'B2C (GURGAON)'),
    ('461', 'PAWAN', '', 'SHARMA', 'B2C', 'B2C (GURGAON)'),
    ('462', 'RAHUL', '', 'JANGID', 'MDO', 'SUPPORT'),
    ('502', 'PARITOSH', '', 'GHOSH', 'PLATING', 'FACTORY'),
    ('506', 'SUROJIT', '', 'DEBNATH', 'POLISH', 'FACTORY'),
    ('508', 'ASHISH', 'KUMAR', 'PAL', 'POLKI SETTING', 'FACTORY'),
    ('510', 'HASAN', '', 'SK', 'FILING', 'FACTORY'),
    ('512', 'SUBRAT', '', 'MONDAL', 'GHAT', 'FACTORY'),
    ('517', 'ASHOK', 'KUMAR', 'KUMAWAT', 'QC', 'FACTORY'),
    ('518', 'PARTHA', '', 'SARDAR', 'LASER OPERATOR', 'FACTORY'),
    ('519', 'SANJAY', '', 'RAJOWAR', 'POLISH & PLATING', 'FACTORY'),
    ('523', 'JAYANTA', '', 'DAS', 'POLKI SETTING', 'FACTORY'),
    ('526', 'ANIL', '', 'GOTHWAL', 'CASTING', 'FACTORY'),
    ('531', 'AMIT', 'KUMAR', 'MONDAL', 'POLKI SETTING', 'FACTORY'),
    ('532', 'BISWAJIT', '', 'ADAK', 'POLKI SETTING', 'FACTORY'),
    ('538', 'VIPLOB', '', 'CHAKROBORTY', 'POLKI SETTING', 'FACTORY'),
    ('539', 'RAHUL', '', 'KUMAWAT', 'B2B-QC', 'B2B'),
    ('543', 'JAYANTA', '', 'BARMAN', 'POLKI SETTING', 'FACTORY'),
    ('565', 'SHIVAM', 'KUMAR', 'UPRATI', 'GHAT', 'FACTORY'),
    ('566', 'GANESH', '', 'DUTTA', 'GHAT', 'FACTORY'),
    ('571', 'CHANDAN', '', 'RAJBHAR', 'DIAMOND ASSORTING', 'FACTORY'),
    ('573', 'ASHOK', '', 'PAREEK', 'QC', 'FACTORY'),
    ('574', 'PABAN', '', 'GHOSH', 'GHAT', 'FACTORY'),
    ('575', 'SAJIJUL', '', '', 'FILING', 'FACTORY'),
    ('577', 'SUMANTA', '', 'DEY', 'BAGGING', 'FACTORY'),
    ('579', 'SANJAY', '', 'RAKSHIT', 'POLKI SETTING', 'FACTORY'),
    ('588', 'SUNIL', 'KUMAR', 'SAIN', 'MICRO SETTING', 'FACTORY'),
    ('596', 'BAPI', '', 'MONDAL', 'POLKI SETTING', 'FACTORY'),
    ('599', 'UMMED', 'SINGH', 'RATHOR', 'ADMIN (MAINTANANCE)', 'FACTORY'),
    ('601', 'POORAN', '', 'RAJBHAR', 'DIAMOND ASSORTING', 'FACTORY'),
    ('607', 'ASIM', '', 'HAZRA', 'GHAT', 'FACTORY'),
    ('617', 'SANKRITAN', '', 'MONDAL', 'FILING', 'FACTORY'),
    ('622', 'SANJAY', '', 'PAL', 'MICRO SETTING', 'FACTORY'),
    ('624', 'VIRENDRA', '', 'SINGH', 'PRODUCTION DEO', 'FACTORY'),
    ('633', 'SWAPAN', '', 'NANDI', 'GHAT', 'FACTORY'),
    ('637', 'MANOJ', '', 'PAL', 'BAGGING', 'FACTORY'),
    ('647', 'PRASENJIT', '', 'DAS', 'POLKI SETTING', 'FACTORY'),
    ('650', 'SANJAY', '', 'VERMA', 'ADMIN', 'FACTORY'),
    ('651', 'RATAN', '', 'DEY', 'GHAT', 'FACTORY'),
    ('657', 'PAPAI', '', 'GHOSH', 'MICRO SETTING', 'FACTORY'),
    ('661', 'SANJAY', '', 'JANGID', 'POLKI SETTING DEO', 'FACTORY'),
    ('662', 'MAHADEB', '', 'BARMAN', 'MICRO SETTING', 'FACTORY'),
    ('663', 'HEMANT', 'KUMAR', 'MAHAWAR', 'REPAIR', 'FACTORY'),
    ('664', 'RANJAN', '', 'BISWAS', 'POLKI SETTING', 'FACTORY'),
    ('669', 'AJAY', 'SINGH', 'JADAOUN', 'COLOR STONE BAGGING', 'FACTORY'),
    ('670', 'ABHIJIT', '', 'DUTTA', 'MICRO SETTING', 'FACTORY'),
    ('671', 'CHINMOY', '', 'SAHA', 'POLKI SETTING', 'FACTORY'),
    ('675', 'GAJANAND', '', 'VERMA', 'PPC', 'FACTORY'),
    ('676', 'KISHORE', 'KUMAR', 'HALDAR', 'PRODUCTION', 'FACTORY'),
    ('678', 'SHIBNATH', '', 'DAS', 'MICRO SETTING', 'FACTORY'),
    ('679', 'SARABINDU', '', 'HAZRA', 'FILING', 'FACTORY'),
    ('684', 'SUBRATA', '', 'DAS', 'POLKI SETTING', 'FACTORY'),
    ('685', 'SAQIB', '', 'KHAN', 'STONE', 'FACTORY'),
    ('694', 'VISHNU', '', 'RAJAWAT', 'LASER MARKING', 'FACTORY'),
    ('695', 'SUBIR', '', '', 'POLISH', 'FACTORY'),
    ('698', 'SANJAY', '', 'GHOSH', 'GHAT', 'FACTORY'),
    ('707', 'RAMESH', 'KUMAR', 'YADAV', 'PRODUCTION', 'FACTORY'),
    ('709', 'BISWAJIT', '', 'MONDAL', 'GHAT', 'FACTORY'),
    ('711', 'CHETAN', '', 'GOENKA', 'PPC', 'FACTORY'),
    ('716', 'GOVIND', 'NARAYAN', 'SAIN', 'MICRO SETTING', 'FACTORY'),
    ('718', 'DINESH', 'KUMAR', 'MEHARA', 'CAD', 'FACTORY'),
    ('729', 'INDRAJIT', '', 'GHOSH', 'POLKI SETTING', 'FACTORY'),
    ('730', 'ANIL', '', 'SONI', 'STONE', 'FACTORY'),
    ('731', 'RAHUL', '', 'SAINI', 'CASTING', 'FACTORY'),
    ('733', 'MUKESH', 'KUMAR', 'SHARMA', 'QC', 'FACTORY'),
    ('738', 'SUKANTA', '', 'BISWAS', 'POLKI SETTING', 'FACTORY'),
    ('739', 'KISHORE', '', 'HALDER', 'POLKI SETTING', 'FACTORY'),
    ('740', 'MANOJ', 'KUMAR', 'SHARMA', 'PRODUCTION', 'FACTORY'),
    ('741', 'PATIRAM', '', 'MONDAL', 'POLISH', 'FACTORY'),
    ('749', 'ROHIT', '', 'SAINI', 'PPC', 'FACTORY'),
    ('752', 'ARIF', '', 'KHAN', 'STONE', 'FACTORY'),
    ('756', 'PURUSHOTAM', '', 'BAIRWA', 'PUWAI', 'FACTORY'),
    ('766', 'DIPAK', '', 'HALDER', 'CAD', 'FACTORY'),
    ('768', 'TOTAN', '', 'MONDAL', 'MICRO SETTING', 'FACTORY'),
    ('770', 'RAJ', '', 'DAS', 'MICRO SETTING', 'FACTORY'),
    ('771', 'SINTU', '', 'DEY', 'POLISH', 'FACTORY'),
    ('772', 'KISHAN', '', 'SONI', 'Q.C DEPARTMENT', 'FACTORY'),
    ('774', 'WASIM', '', 'AKTAR', 'FILLING', 'FACTORY'),
    ('776', 'UMANG', '', 'GUPTA', 'INVENTORY', 'FACTORY'),
    ('777', 'RAVI', '', 'SAINI', 'COLOR STONE BAGGING', 'FACTORY'),
    ('778', 'LAKHAN', '', 'MURMU', 'REPAIR', 'FACTORY'),
    ('779', 'CHANDAN', '', 'SINGH', 'QC', 'FACTORY'),
    ('780', 'AJAY', 'KUMAR', 'PANCHAL', 'DATA ENTRY OPERATOR', 'FACTORY'),
    ('781', 'RAKESH', '', 'DEY', 'FILLING', 'FACTORY'),
    ('782', 'BANTI', '', 'MEENA', 'FILLING', 'FACTORY'),
    ('783', 'GOBINDO', '', 'HAZRA', 'FILLING', 'FACTORY'),
    ('784', 'BHUBAN', '', 'DEY', 'FILLING', 'FACTORY'),
    ('785', 'KUMAR', '', 'MITRA', 'FILLING', 'FACTORY'),
    ('786', 'BISHNU', '', 'GHOSH', 'CAD', 'FACTORY'),
    ('787', 'RANJIT', '', 'BISWAS', 'LASER', 'FACTORY'),
    ('788', 'ANIL', 'KUMAR', 'BAIRWA', 'REPAIR', 'FACTORY'),
    ('789', 'DEEPAK', 'KUMAR', 'BAIRWA', 'CASTING', 'FACTORY')
;

  INSERT INTO departments (tenant_id, name)
  SELECT DISTINCT v_tenant_id, m.department
  FROM _raniwala_master m
  WHERE m.department <> ''
  ON CONFLICT (tenant_id, name) DO NOTHING;

  UPDATE profiles p
  SET first_name = m.first_name,
      middle_name = m.middle_name,
      last_name = m.last_name,
      department = CASE WHEN m.department <> '' THEN m.department ELSE p.department END,
      division = CASE WHEN m.division <> '' THEN m.division ELSE p.division END
  FROM _raniwala_master m
  WHERE p.tenant_id = v_tenant_id
    AND p.essl_employee_code = m.emp_code;

  GET DIAGNOSTICS v_matched = ROW_COUNT;
  RAISE NOTICE 'Raniwala employee rename: % profiles matched and updated by essl_employee_code', v_matched;
END $$;
